dist: bionic
language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
script:
  - cargo fmt --verbose --all -- --check --verbose
  - cargo clippy --verbose --all -- --verbose
  - cargo build --verbose --all
  - cargo test --verbose --all
before_install:
  - rustup component add rustfmt
  - rustup component add clippy
